// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3a7Q9F7-zIAxBzoUoksc-0FSWdlj0i8',
    appId: '1:188908446406:web:b9dd6068dbd08530242dc7',
    messagingSenderId: '188908446406',
    projectId: 'serviceapp-37d3a',
    authDomain: 'serviceapp-37d3a.firebaseapp.com',
    storageBucket: 'serviceapp-37d3a.firebasestorage.app',
    measurementId: 'G-5WD87SV8NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR83JdbgIV-jt4p2id6oxNtLXvVCp7Q48',
    appId: '1:188908446406:android:b1c03a0d2e45a626242dc7',
    messagingSenderId: '188908446406',
    projectId: 'serviceapp-37d3a',
    storageBucket: 'serviceapp-37d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLb3hWZYYJZ2XPYiHXJdLdz4OgCaaRrjw',
    appId: '1:188908446406:ios:2a39eecdc00a322e242dc7',
    messagingSenderId: '188908446406',
    projectId: 'serviceapp-37d3a',
    storageBucket: 'serviceapp-37d3a.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLb3hWZYYJZ2XPYiHXJdLdz4OgCaaRrjw',
    appId: '1:188908446406:ios:2a39eecdc00a322e242dc7',
    messagingSenderId: '188908446406',
    projectId: 'serviceapp-37d3a',
    storageBucket: 'serviceapp-37d3a.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ3a7Q9F7-zIAxBzoUoksc-0FSWdlj0i8',
    appId: '1:188908446406:web:f78d5060fe7232f9242dc7',
    messagingSenderId: '188908446406',
    projectId: 'serviceapp-37d3a',
    authDomain: 'serviceapp-37d3a.firebaseapp.com',
    storageBucket: 'serviceapp-37d3a.firebasestorage.app',
    measurementId: 'G-1H3EPZ5KY5',
  );

}