// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPcPzsCfBKsvyv-RlaAR14Fvhtay0izYk',
    appId: '1:25497098644:web:a6ca808417f2c9a263d781',
    messagingSenderId: '25497098644',
    projectId: 'service-d8678',
    authDomain: 'service-d8678.firebaseapp.com',
    storageBucket: 'service-d8678.firebasestorage.app',
    measurementId: 'G-QESHBBHQ4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDGslwnSdVaBSJmSJFSm9RQO2d9c-Ors',
    appId: '1:25497098644:android:5e81e24b2137a7b663d781',
    messagingSenderId: '25497098644',
    projectId: 'service-d8678',
    storageBucket: 'service-d8678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdD6MOroYDMhZCbf4b-__Xehwp0-t1fw',
    appId: '1:25497098644:ios:d076620a2a06b36463d781',
    messagingSenderId: '25497098644',
    projectId: 'service-d8678',
    storageBucket: 'service-d8678.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdD6MOroYDMhZCbf4b-__Xehwp0-t1fw',
    appId: '1:25497098644:ios:d076620a2a06b36463d781',
    messagingSenderId: '25497098644',
    projectId: 'service-d8678',
    storageBucket: 'service-d8678.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPcPzsCfBKsvyv-RlaAR14Fvhtay0izYk',
    appId: '1:25497098644:web:f409cb956a7e750863d781',
    messagingSenderId: '25497098644',
    projectId: 'service-d8678',
    authDomain: 'service-d8678.firebaseapp.com',
    storageBucket: 'service-d8678.firebasestorage.app',
    measurementId: 'G-KDQ8266SEC',
);

}